cloneConcurrency: 8
defaultSemverRangePrefix: ''
enableScripts: false
enableTelemetry: false
httpRetry: 3
httpTimeout: 60000
nmMode: hardlinks-global
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.5.1.cjs
